app.url=https://tutorialsninja.com/demo/index.php?route=common/home
browser=chrome
headless=false
implicit.wait=10
explicit.wait=15
page.load.timeout=30
screenshot.on.failure=true
screenshot.dir=target/screenshots
extent.report.dir=target/extent-reports

firstname=John
lastname=Doe
email=johndoe12345@test.com
telephone=9876543210
password=Test@1234
confirmpassword=Test@1234
